spring:
  redis:
    host: super-os
    password: 2pmnpw47
  web:
    resources:
      static-locations: /static/
  thymeleaf:
    #    prefix: /static/
    prefix: classpath:/
    cache: false
  data:
    mongodb:
      #      uri: mongodb://mongo-admin:6d2880f9f562108b@super-os:27017/?authSource=admin
      username: mongo-admin
      password: 6d2880f9f562108b
      port: 27017
      host: super-os
      database: applets
      authentication-database: admin
